package com.zoo.web.entity;
// Generated 04-nov-2018 23:59:38 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Animal generated by hbm2java
 */
@Entity
@Table(name = "animal")
public class Animal implements java.io.Serializable {

	private Integer codigo;
	private Sector sector;
	private Tipo tipo;
	private String nombre;
	private int peso;
	private String genero;
	private Date fechaNacimiento;
	private Date fechaIngreso;
	private Date fechaDefuncion;

	public Animal() {
	}

	public Animal(Sector sector, Tipo tipo, String nombre, int peso, String genero, Date fechaIngreso) {
		this.sector = sector;
		this.tipo = tipo;
		this.nombre = nombre;
		this.peso = peso;
		this.genero = genero;
		this.fechaIngreso = fechaIngreso;
	}

	public Animal(Sector sector, Tipo tipo, String nombre, int peso, String genero, Date fechaNacimiento,
			Date fechaIngreso, Date fechaDefuncion) {
		this.sector = sector;
		this.tipo = tipo;
		this.nombre = nombre;
		this.peso = peso;
		this.genero = genero;
		this.fechaNacimiento = fechaNacimiento;
		this.fechaIngreso = fechaIngreso;
		this.fechaDefuncion = fechaDefuncion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "codigo", unique = true, nullable = false)
	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_sector", nullable = false)
	public Sector getSector() {
		return this.sector;
	}

	public void setSector(Sector sector) {
		this.sector = sector;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo", nullable = false)
	public Tipo getTipo() {
		return this.tipo;
	}

	public void setTipo(Tipo tipo) {
		this.tipo = tipo;
	}

	@Column(name = "nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "peso", nullable = false)
	public int getPeso() {
		return this.peso;
	}

	public void setPeso(int peso) {
		this.peso = peso;
	}

	@Column(name = "genero", nullable = false, length = 10)
	public String getGenero() {
		return this.genero;
	}

	public void setGenero(String genero) {
		this.genero = genero;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_nacimiento", length = 10)
	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_ingreso", nullable = false, length = 10)
	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_defuncion", length = 10)
	public Date getFechaDefuncion() {
		return this.fechaDefuncion;
	}

	public void setFechaDefuncion(Date fechaDefuncion) {
		this.fechaDefuncion = fechaDefuncion;
	}

}
